export const calculatorRoutes = [
    { path: '/calculator/length', component: 'ConversionCalc', calcType: 'length' },
    { path: '/calculator/temperature', component: 'ConversionCalc', calcType: 'temperature' },
    { path: '/calculator/volume', component: 'ConversionCalc', calcType: 'volume' },
    { path: '/calculator/weight', component: 'ConversionCalc', calcType: 'weight' },
    { path: '/calculator/time', component: 'ConversionCalc', calcType: 'time' },
    { path: '/calculator/sphereVolume', component: 'VolumeCalc', calcType: 'sphereVolume' },
    { path: '/calculator/coneVolume', component: 'VolumeCalc', calcType: 'coneVolume' },
    { path: '/calculator/cubeVolume', component: 'VolumeCalc', calcType: 'cubeVolume' },
    { path: '/calculator/cylinderVolume', component: 'VolumeCalc', calcType: 'cylinderVolume' },
    { path: '/calculator/rectangleVolume', component: 'VolumeCalc', calcType: 'rectangleVolume' },
    { path: '/calculator/rectangleArea', component: 'AreaCalc', calcType: 'rectangleArea' },
    { path: '/calculator/triangleArea', component: 'AreaCalc', calcType: 'triangleArea' },
    { path: '/calculator/trapezoidArea', component: 'AreaCalc', calcType: 'trapezoidArea' },
    { path: '/calculator/circleArea', component: 'AreaCalc', calcType: 'circleArea' },
    { path: '/calculator/sectorArea', component: 'AreaCalc', calcType: 'sectorArea' },
];
