export const calculatorRoutes = [
    // Area Calculators
    { path: '/calculator/areaRectangle', calcType: 'areaRectangle' },
    { path: '/calculator/areaTriangle', calcType: 'areaTriangle' },
    { path: '/calculator/areaTrapezoid', calcType: 'areaTrapezoid' },
    { path: '/calculator/areaCircle', calcType: 'areaCircle' },
    { path: '/calculator/areaSector', calcType: 'areaSector' },
    { path: '/calculator/areaParallelogram', calcType: 'areaParallelogram' },
    { path: '/calculator/areaRhombus', calcType: 'areaRhombus' },
    { path: '/calculator/areaSquare', calcType: 'areaSquare' },
    { path: '/calculator/areaEllipse', calcType: 'areaEllipse' },
    // Distance Calculators
    { path: '/calculator/distance2D', calcType: 'distance2D' },
    { path: '/calculator/distanceMidpoint', calcType: 'distanceMidpoint' },
    { path: '/calculator/distanceSlope', calcType: 'distanceSlope' },
    // Exponent Calculators
    { path: '/calculator/basicExponent', calcType: 'basicExponent' },
    { path: '/calculator/fractionalExponent', calcType: 'fractionalExponent' },
    { path: '/calculator/negativeExponent', calcType: 'negativeExponent' },
    { path: '/calculator/squareRoot', calcType: 'squareRoot' },
    { path: '/calculator/nthRoot', calcType: 'nthRoot' },
    // Percentage Calculators
    { path: '/calculator/percentageOf', calcType: 'percentageOf' },
    { path: '/calculator/increaseByPercentage', calcType: 'increaseByPercentage' },
    { path: '/calculator/decreaseByPercentage', calcType: 'decreaseByPercentage' },
    { path: '/calculator/percentageIncrease', calcType: 'percentageIncrease' },
    { path: '/calculator/percentageDecrease', calcType: 'percentageDecrease' },
    { path: '/calculator/percentageOfTotal', calcType: 'percentageOfTotal' },
    // Perimeter Calculators
    { path: '/calculator/perimeterTriangle', calcType: 'perimeterTriangle' },
    { path: '/calculator/perimeterCircle', calcType: 'perimeterCircle' },
    { path: '/calculator/perimeterParallelogram', calcType: 'perimeterParallelogram' },
    { path: '/calculator/perimeterRectangle', calcType: 'perimeterRectangle' },
    { path: '/calculator/perimeterRhombus', calcType: 'perimeterRhombus' },
    { path: '/calculator/perimeterSquare', calcType: 'perimeterSquare' },
    // Surface Area Calculators
    { path: '/calculator/surfaceAreaSphere', calcType: 'surfaceAreaSphere' },
    { path: '/calculator/surfaceAreaCone', calcType: 'surfaceAreaCone' },
    { path: '/calculator/surfaceAreaCube', calcType: 'surfaceAreaCube' },
    { path: '/calculator/surfaceAreaCylinder', calcType: 'surfaceAreaCylinder' },
    { path: '/calculator/surfaceAreaRectangularPrism', calcType: 'surfaceAreaRectangularPrism' },
    { path: '/calculator/surfaceAreaHemisphere', calcType: 'surfaceAreaHemisphere' },
    { path: '/calculator/surfaceAreaPyramid', calcType: 'surfaceAreaPyramid' },
    { path: '/calculator/surfaceAreaPipe', calcType: 'surfaceAreaPipe' },
    { path: '/calculator/surfaceAreaTriangularPrism', calcType: 'surfaceAreaTriangularPrism' },
    { path: '/calculator/baseSurfaceAreaCone', calcType: 'baseSurfaceAreaCone' },
    { path: '/calculator/lateralSurfaceAreaCone', calcType: 'lateralSurfaceAreaCone' },
    { path: '/calculator/baseSurfaceAreaPyramid', calcType: 'baseSurfaceAreaPyramid' },
    { path: '/calculator/lateralSurfaceAreaPyramid', calcType: 'lateralSurfaceAreaPyramid' },
    // Volume Calculators
    { path: '/calculator/volumeSphere', calcType: 'volumeSphere' },
    { path: '/calculator/volumeCone', calcType: 'volumeCone' },
    { path: '/calculator/volumeCube', calcType: 'volumeCube' },
    { path: '/calculator/volumeCylinder', calcType: 'volumeCylinder' },
    { path: '/calculator/volumeRectangularPrism', calcType: 'volumeRectangularPrism' },
    { path: '/calculator/volumeHemisphere', calcType: 'volumeHemisphere' },
    { path: '/calculator/volumePyramid', calcType: 'volumePyramid' },
    { path: '/calculator/volumePipe', calcType: 'volumePipe' },
    { path: '/calculator/volumeTriangularPrism', calcType: 'volumeTriangularPrism' },
];
